---

- name: Install bash-completion for ansible
  get_url:
    url: https://raw.githubusercontent.com/dysosmus/ansible-completion/master/{{ item }}
    dest: /etc/bash_completion.d/{{ item }}
    mode: '644'
    owner: 'root'
    group: 'root'
    force_basic_auth: yes
  become: yes
  with_items: 
    - ansible-completion.bash
    - ansible-doc-completion.bash
    - ansible-galaxy-completion.bash
    - ansible-playbook-completion.bash
    - ansible-pull-completion.bash
    - ansible-vault-completion.bash